---
title: "HW 0"
output:
  html_document
---

```{r global_options, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(eval = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
```


*Note*: This will be the only assignment that will not be done using R/RStudio. For this assignment only, you can use Word or hand-written comments. 

1. Read through all of your syllabi. For each, identify one unique characteristics about each class. 

2. Make a calendar of the important dates, which include midterms, exams, or the due dates for major papers. Due this for each class. Send a picture of your calendar (cell phone is fine) prior to class, where it's clear you have each deadline labelled appropriate for each class.

3. Read the following two articles: [Sabermetric Manifesto](http://www.seanlahman.com/baseball-archive/sabermetrics/sabermetric-manifesto/) and [The Moneyball Revolution](http://www.slate.com/articles/sports/the_next_20/2016/09/fire_joe_morgan_and_the_moneyball_revolution.html)

The following questions refer to the articles above, and perhaps some general sports knowledge. 

4. Our class starts with baseball statistics. What about baseball -- and baseball stats -- makes it the most reasonable starting point? 

5. Think of a metric in a sport besides baseball that is (i) strongly linked to winning and also mostly driven by individual contribution, (ii) strongly linked to winning but not driven by individual contribution, (iii) not strongly linked to winning but mostly driven by individual contribution. Do not use any examples discussed in class. 
6. ERA is a measure of how many runs a pitcher gives up. What are some factors -- outside of a players' control --  that the article lists as impacting ERA?

7. Pick a few ways in which folks studying statistics in baseball are described in the Fire Joe Morgan article. Why is there this animosity?

8. Why was Tim McCarver right? 
